librari/librari/urls.py
from django.contrib import admin
from django.urls import path,include
from login.views import loginview,signupview,logoutview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("pages.urls")),
    path('login/',loginview,name="login"),
    path('logout/',logoutview,name="logout"),
    path('signup/',signupview,name="signup"),
]

librari/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('', views.loginview, name="login"),
]

librari/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path('',views.home,name="home"),
    path('book/<int:book_id>/',views.detail,name="detail"),
    path('book/<int:book_id>/add/',views.addToCart,name="addToCart"),
    path('book/<int:book_id>/remove/',views.removeFromCart,name="removeFromCart"),
    path('cart/',views.cart,name="cart"),
    path('search/',views.searchview,name="search")
]

librari/Cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Cart(models.Model):
    cart = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def get_total(self):
        total = 0
        for book in self.book_set.all():
            total += float(book.cmimi)
        return round(total,2)

@receiver(post_save, sender=User)
def create_cart(sender, instance, created, **kwargs):
    if created:
        Cart.objects.create(cart=instance)

@receiver(post_save, sender=User)
def save_cart(sender, instance, **kwargs):
    instance.cart.save()

librari/Cart/views.py
from django.shortcuts import render

# Create your views here.

librari/pages/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Dyqani Librave</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Little Closet template">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/bootstrap-4.1.2/bootstrap.min.css' %}">
<link href="{% static 'pages/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'pages/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pages/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pages/plugins/OwlCarousel2-2.2.1/animate.css' %}">
{% block custom_css %}
{% endblock %}
</head>
<body>

<!-- Menu -->

<div class="menu">

	<!-- Search -->
	<div class="menu_search">
		<form action="/search/" method="post" id="menu_search_form" class="menu_search_form">
			{% csrf_token %}
			{{ form.searchText }}
			<button class="menu_search_button"><img src="{% static 'pages/images/search.png' %}" alt=""></button>
		</form>
	</div>
	<!-- Navigation -->
	<div class="menu_nav">
		<ul>
			<li><a href="#">Libra</a></li>

		</ul>
	</div>
	<!-- Contact Info -->
	<div class="menu_contact">
		<div class="menu_phone d-flex flex-row align-items-center justify-content-start">
			<div><div><img src="{% static 'pages/images/phone.svg' %}" alt="https://www.flaticon.com/authors/freepik"></div></div>
			<div>+1 912-252-7350</div>
		</div>
		<div class="menu_social">
			<ul class="menu_social_list d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
</div>

<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="header_overlay"></div>
		<div class="header_content d-flex flex-row align-items-center justify-content-start">
			<div class="logo">
				<a href="#">
					<div class="d-flex flex-row align-items-center justify-content-start">
						<div><img src="{% static 'pages/images/logo_1.png' %}" alt=""></div>
						<div>Dyqani Librave</div>
					</div>
				</a>
			</div>
			<div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
			<nav class="main_nav">
				<ul class="d-flex flex-row align-items-start justify-content-start">
					<li class="active"><a href="#">Libra</a></li>

				</ul>
			</nav>
			<div class="header_right d-flex flex-row align-items-center justify-content-start ml-auto">
				<!-- Search -->
				<div class="header_search">
					<form action="/search/" method="post" id="header_search_form">
						{% csrf_token %}
						{{ form.searchText }}
						<button class="header_search_button"><img src="{% static 'pages/images/search.png' %}" alt=""></button>
					</form>
				</div>
				{% if user.is_authenticated %}
				<!-- User -->
				<div class="user"><a style="display:inline-block" href="#"><div><img src="{% static 'pages/images/user.svg' %}" alt="https://www.flaticon.com/authors/freepik"></div></a><span>{{ user.username }}</span><a href="/logout" style="margin-left: 5px;">Log out</a></div>
				{% else %}
				<a style="margin-right:12px" href="/login">Log in</a>
				{% endif %}
				<!-- Cart -->
				<div class="cart"><a href="{% url 'pages:cart' %}"><div><img class="svg" src="{% static 'pages/images/cart.svg' %}" alt="https://www.flaticon.com/authors/freepik"></div></a></div>
				<!-- Phone -->
				<div class="header_phone d-flex flex-row align-items-center justify-content-start">
					<div><div><img src="{% static 'pages/images/phone.svg' %}" alt="https://www.flaticon.com/authors/freepik"></div></div>
					<div>+1 912-252-7350</div>
				</div>
			</div>
		</div>
	</header>

	<div class="super_container_inner">
		<div class="super_overlay"></div>

        {% block content %}
        {% endblock %}


		<!-- Footer -->

		<footer class="footer">
			<div class="footer_content">
				<div class="container">
					<div class="row">

						<!-- About -->
						<div class="col-lg-4 footer_col">
							<div class="footer_about">
								<div class="footer_logo">
									<a href="#">
										<div class="d-flex flex-row align-items-center justify-content-start">
											<div class="footer_logo_icon"><img src="{% static 'pages/images/logo_2.png' %}" alt=""></div>
											<div>Dyqani Librave</div>
										</div>
									</a>
								</div>
								<div class="footer_about_text">
									<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Fusce venenatis vel velit vel euismod.</p>
								</div>
							</div>
						</div>

						<!-- Footer Links -->
						<div class="col-lg-4 footer_col">
							<div class="footer_menu">
								<div class="footer_title">Support</div>
								<ul class="footer_list">
									<li>
										<a href="#"><div>Customer Service<div class="footer_tag_1">online now</div></div></a>
									</li>
									<li>
										<a href="#"><div>Return Policy</div></a>
									</li>
									<li>
										<a href="#"><div>Size Guide<div class="footer_tag_2">recommended</div></div></a>
									</li>
									<li>
										<a href="#"><div>Terms and Conditions</div></a>
									</li>
									<li>
										<a href="#"><div>Contact</div></a>
									</li>
								</ul>
							</div>
						</div>

						<!-- Footer Contact -->
						<div class="col-lg-4 footer_col">
							<div class="footer_contact">
								<div class="footer_title">Stay in Touch</div>
								<div class="newsletter">
									<form action="#" id="newsletter_form" class="newsletter_form">
										<input type="email" class="newsletter_input" placeholder="Subscribe to our Newsletter" required="required">
										<button class="newsletter_button">+</button>
									</form>
								</div>
								<div class="footer_social">
									<div class="footer_title">Social</div>
									<ul class="footer_social_list d-flex flex-row align-items-start justify-content-start">
										<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
										<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
										<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="footer_bar">
				<div class="container">
					<div class="row">
						<div class="col">
							<div class="footer_bar_content d-flex flex-md-row flex-column align-items-center justify-content-start">
								<div class="copyright order-md-1 order-2"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
								<nav class="footer_nav ml-md-auto order-md-2 order-1">
									<ul class="d-flex flex-row align-items-center justify-content-start">
										<li><a href="category.html">Libra</a></li>

										<li><a href="#">Contact</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
	</div>

</div>
<script src="{% static 'pages/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'pages/styles/bootstrap-4.1.2/popper.js' %}"></script>
<script src="{% static 'pages/styles/bootstrap-4.1.2/bootstrap.min.js' %}"></script>
<script src="{% static 'pages/plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'pages/plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'pages/plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'pages/plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'pages/plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'pages/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'pages/plugins/easing/easing.js' %}"></script>
<script src="{% static 'pages/plugins/progressbar/progressbar.min.js' %}"></script>
<script src="{% static 'pages/plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'pages/js/custom.js' %}"></script>
</body>
</html>

librari/pages/templates/pages/cart.html
{% extends 'pages/base.html' %}
{% load static %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/cart.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/cart_responsive.css' %}">
{% endblock %}

{% block content %}
		<!-- Cart -->
		<div style="margin-top:20px" class="cart_section">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="cart_container">
							
							<!-- Cart Bar -->
							<div class="cart_bar">
								<ul class="cart_bar_list item_list d-flex flex-row align-items-center justify-content-end">
									<li class="mr-auto">Product</li>
									<li>Price</li>
								</ul>
							</div>

							<!-- Cart Items -->
							<div class="cart_items">
								<ul class="cart_items_list">

									{% for book in books %}
									<!-- Cart Item -->
									<li class="cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-end justify-content-start">
										<div class="product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start mr-auto">
											<div><div class="product_number">{{ forloop.counter }}</div></div>
											<div><div class="product_image"><img src="{{ book.img_src }}" alt=""></div></div>
											<div class="product_name_container">
												<div class="product_name"><a href="{% url 'pages:detail' book.id %}">{{ book.titulli }}, {{ book.viti }}</a></div>
												<div class="product_text">{{ book.autori }}</div>
											</div>
										</div>
										<a href="{% url 'pages:removeFromCart' book.id %}" style="margin-right: 20px;">Remove</a>
										<div class="product_price product_text"><span>Price: </span>${{ book.cmimi }}</div>
									</li>
									{% endfor %}
								</ul>
							</div>
							<h3 style="text-align: right;margin: 15px;"> Total: ${{ total }}</h3>
							<!-- Cart Buttons -->
							<div class="cart_buttons d-flex flex-row align-items-start justify-content-start">
								<div class="cart_buttons_inner ml-sm-auto d-flex flex-row align-items-start justify-content-start flex-wrap">
									<div class="button button_continue trans_200"><a href="/">continue shopping</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

librari/pages/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/responsive.css' %}">
{% endblock %}

{% block content %}

<!-- Products -->
<div class="products">
	<div class="container">
		<div class="row products_row">
		{% for book in books %}
		<div class="col-xl-4 col-md-6">
			<div class="product">
				<div class="product_image"><img src="{{ book.img_src }}" alt=""></div>
							<div class="product_content">
								<div class="product_info d-flex flex-row align-items-start justify-content-start">
									<div>
										<div>
											<div class="product_name"><a href="{% url 'pages:detail' book.id %}">{{ book.titulli }}</a></div>
											<div class="product_category"><a href="category.html">{{ book.autori }}</a></div>
										</div>
									</div>
									<div class="ml-auto text-right">
										<div class="product_price text-right">${{ book.cmimi }}</span></div>
									</div>
								</div>
								<div class="product_buttons">
									<div class="text-right d-flex flex-row align-items-start justify-content-start">
										<a id="cart" href="{% url 'pages:addToCart' book.id %}" style="display:block;width:100%;height:100%;border-top: 1px solid #ededed;padding: 5px;">
										<div class="product_button product_cart text-center d-flex flex-column align-items-center justify-content-center">
											<div><div><img src="{% static 'pages/images/cart.svg' %}" class="svg" alt=""><div>+</div></div></div>
										</div>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
		{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

librari/pages/templates/pages/product.html
{% extends 'pages/base.html' %}
{% load static %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/product.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pages/styles/product_responsive.css' %}">
{% endblock %}

{% block content %}
<!-- Product -->
<div class="product">
	<div class="container">
		<div class="row">
			<!-- Product Image -->
			<div class="col-lg-6">
				<img style="width:60%;" src="{{ book.img_src }}" draggable="false">
			</div>

			<!-- Product Info -->
			<div class="col-lg-6 product_col">
				<div class="product_info">
					<div class="product_name">{{ book.titulli }}</div>
						<div class="product_category"><a href="category.html">{{ book.autori }}</a></div>
						<div class="product_price">${{ book.cmimi }}</span></div>
						<div class="product_buttons">
							<div class="text-right d-flex flex-row align-items-start justify-content-start">
							<a id="cart" href="{% url 'pages:addToCart' book.id %}" style="display:block;width:100%;border: 1px solid #ededed;padding: 5px;">
							<div class="product_button product_cart text-center d-flex flex-column align-items-center justify-content-center">
							<div><div><img src="{% static 'pages/images/cart.svg' %}" class="svg" alt=""><div>+</div></div></div>
							</div>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}